language: java
script: gradle dist

# Hack dummy values into the gradle properties
install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: H6NOypPed/orlWgR/VQadEDDHOh/QEW+TTuDazJhimHL6C423C9gcXsgPbPTOordG8kxWm5fGbVoHmPkvBhkPigGoCkCHouhHUfRKldCeh3voq8AM7kIj/EmSnIyor15wP1LRBgORESyzVaapG0K4IRo5TP1gQl2fZorFwwXIVc=
  file: build/distributions/xmlresolver-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: ndw/xmlresolver
    branch: master
